version: '3.8'

services:
  elasticsearch-master:
    container_name: elasticsearch-master
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - node.name=elasticsearch-master
      - cluster.name=elasticsearch-cluster
      - discovery.seed_hosts=elasticsearch-node1,elasticsearch-node2
      - cluster.initial_master_nodes=elasticsearch-master,elasticsearch-node1,elasticsearch-node2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=zen
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch-master:/usr/share/elasticsearch/data:z
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  elasticsearch-node1:
    container_name: elasticsearch-node1
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - node.name=elasticsearch-node1
      - cluster.name=elasticsearch-cluster
      - discovery.seed_hosts=elasticsearch-master,elasticsearch-node2
      - cluster.initial_master_nodes=elasticsearch-master,elasticsearch-node1,elasticsearch-node2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=zen
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch-node1:/usr/share/elasticsearch/data:z
    ports:
      - "9201:9200"
      - "9301:9300"
    networks:
      - elk

  elasticsearch-node2:
    container_name: elasticsearch-node2
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - node.name=elasticsearch-node2
      - cluster.name=elasticsearch-cluster
      - discovery.seed_hosts=elasticsearch-master,elasticsearch-node1
      - cluster.initial_master_nodes=elasticsearch-master,elasticsearch-node1,elasticsearch-node2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=zen
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch-node2:/usr/share/elasticsearch/data:z
    ports:
      - "9202:9200"
      - "9302:9300"
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch-master:
  elasticsearch-node1:
  elasticsearch-node2:
